# Generated by Django 5.1.3 on 2024-11-12 09:25

import uploadmanager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', validators=[uploadmanager.models.validate_file_type, uploadmanager.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('img', 'Image'), ('vid', 'Video')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'folder', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'is_parent', 'user')},
        ),
    ]
