# Generated by Django 5.1.3 on 2024-11-13 15:45

import uploadmanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadmanager', '0003_alter_file_folder_alter_file_user_alter_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, validators=[uploadmanager.models.validate_name]),
        ),
    ]
